### ISSUE TITLE
Update conda and docker images

### ISSUE THREAD

**Issue by TedBrookings** [rwdavies/STITCH#100]
Hi @Zilong-Li, I noticed that you released 1.7.1 on Aug 14, which fixes a bug that I just discovered is affecting me. However the conda and docker images aren't updated yet. Is it possible to trigger those updates on your end?

**Comment by Zilong-Li** [comment]
ah, yes, I can update bioconda tomorrow. thanks for reminding me.

**Comment by Zilong-Li** [comment]
`r-stitch == 1.7.1` is on bioconda now
