### ISSUE TITLE
Error in STITCH - Execution halted

### ISSUE THREAD

**Issue by vigneshravi** [rwdavies/STITCH#14]
I have installed STITCH using the recommended workflow. I am trying to execute the test script on the test bams but encounter the following error. 
Any help to understand this error and solve is much appreciated!

```
bash-4.2$ ./STITCH.R --chr=chr19 --bamlist=bamlist.txt --posfile=pos.txt --genfile=gen.txt --outputdir=./ --K=4 --nGen=100 --nCores=1
Error in STITCH(chr = opt$chr, posfile = opt$posfile, K = opt$K, nGen = opt$nGen,  :
  unused arguments (reference_shuffleHaplotypeIterations = eval(parse(text = opt$reference_shuffleHaplotypeIterations)), useTempdirWhileWriting = opt$useTempdirWhileWriting, output_haplotype_dosages = opt$output_haplotype_dosages)
Execution halted

```

**Comment by rwdavies** [comment]
Argh, my bad. Simple answer is to git checkout to the last release commit i.e. 
```git checkout 46d68218ed3e16fa60f635d3366621cff430ed59```
then it should make the CLI file match the last release (this just worked for me and corrected your error). Longer answer is that the CLI function isn't included in the release and tracks the master branch, and I've pushed some stuff to master that I should clearly bundle into a release

**Comment by rwdavies** [comment]
Hey, did this fix the issue for you?

**Comment by d2389758** [comment]
Hi,
I ran into the same issue and it was fixed after git checkout.
Thank you again!

**Comment by rwdavies** [comment]
This should now be fixed with the new version. I'll close this once the new version is up on bioconda.

**Comment by rwdavies** [comment]
OK, I had to release another version to fix bioconda problems, but this should be sorted now. I'll try harder to avoid making changes to the API on master between releases next time

**Comment by vigneshravi** [comment]
Version 1.5.6 helped fix the error I posted. 
Thank you!
