### ISSUE TITLE
Error in if ((r < 0.9) | (1.1 < r))

### ISSUE THREAD

**Issue by Zilong-Li** [rwdavies/STITCH#19]
Hi, Robbie

A small bug came to the surface when I tried to impute a small number samples with STITCH_1.5.3.0008. 

```
Error in if ((r < 0.9) | (1.1 < r)) { :
  missing value where TRUE/FALSE needed
Calls: STITCH_again ... mclapply -> lapply -> FUN -> calculate_gp_t_from_fbsoL
```
The reason is that NULL is assigned to variable r. Maybe this bug also exists in the latest version.

**Comment by rwdavies** [comment]
Hey Zilong, 

Do you want to send me an email with more details? This is not a good sign and something probably went wrong with that version that I'm happy to help debug 

Robbie
