### ISSUE TITLE
error about 1.6.1

### ISSUE THREAD

**Issue by Zilong-Li** [rwdavies/STITCH#27]
Hey Robbie, 

Recently I want to test the performance of latest STITCH. It seems that the 1.6.2 version has not been released on github yet, though the README shows a guide to wget it. So I downloaded the 1.6.1 version and run some tests. Here is a error.
```
Error in data.table::fread(cmd = command, colClasses = colClasses, sep = " ",  :
  unused argument (cmd = command)
Calls: STITCH ... extract_validate_and_load_haplotypes -> <Anonymous>
Execution halted
```
I checked that the version of data.table on my server is 1.11.4. Is it a bug of data.table or of STITCH?

**Comment by rwdavies** [comment]
Shoot, I forgot to put the new version online before I went on holiday. One sec

**Comment by rwdavies** [comment]
OK, I've pushed the new version (sorry about that! I had it on my todo list. Now, to bioconda)

The error above seems like a data.table problem, the "cmd" option only came in later versions of data.table. However this should no longer be a problem in the latest release as I wrote a native R + cpp haplotype file ingester. Let me know if it sorts it for you?

**Comment by Zilong-Li** [comment]
The latest version works and starts to do EM ! Thank u.
