### ISSUE TITLE
STITCH requires openblas, seems to be incompatible with openblas 0.3.8 (latest version)

### ISSUE THREAD

**Issue by TeresaPegan** [rwdavies/STITCH#31]
Hello,

I installed STITCH with the instructions for conda installation from this site, and found that it gave this error:

> library("STITCH")
Loading required package: parallel
Loading required package: rrbgen
Error: package or namespace load failed for ‘STITCH’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/anaconda3/envs/r/lib/R/library/STITCH/libs/STITCH.dylib':
  dlopen(/anaconda3/envs/r/lib/R/library/STITCH/libs/STITCH.dylib, 6): Library not loaded: @rpath/libopenblasp-r0.3.7.dylib
  Referenced from: /anaconda3/envs/r/lib/R/library/STITCH/libs/STITCH.dylib
  Reason: image not found
Execution halted

I was able to get the program running by installing openblas, which I didn't have yet:

`conda install -c conda-forge openblas`

A few days ago, I updated all my conda packages and STITCH started giving me the exact same error again, even though openblas was already installed. After a bunch of iterations of forcing STITCH and openblas (and even R) to re-install, I realized that a new version of openblas - 0.3.8 -  had just been released and it was installed when I did the update. For some reason, STITCH kept trying to use 0.3.7 (according to the error pasted above). The only way I was able to get it working was to downgrade openblas to 0.3.7.

I've got STITCH working again, but hopefully it's helpful for you to know that this happened with the openblas update.

Thanks!

**Comment by rwdavies** [comment]
Thanks, I haven't done a new conda release in a while, so will look into this. Apologies, this must have been very annoying, but thanks for sorting out hopefully what the problem is

**Comment by rwdavies** [comment]
OK, I seem to have updated the bioconda. Can you please check if this solves the problem? I just tried this on one of my machines (not a very clean one, one with a lot of things installed), and it worked (and used openblas-0.3.6)
https://github.com/bioconda/bioconda-recipes/pull/20532

**Comment by TeresaPegan** [comment]
Yes, that does fix it in my base environment, thanks!
