### ISSUE TITLE
Error when using specific number of cores

### ISSUE THREAD

**Issue by fbartusch** [rwdavies/STITCH#35]
Hello,

Beside finding out good working combinations of nCores and memory on our cluster, we experienced a problem when using Stitch 1.6.3 with 20 cores, K=20.

```
[...]
[2020-04-05 11:23:20] Start EM
[2020-04-05 11:23:20] Number of samples: 397
[2020-04-05 11:23:20] Number of SNPs: 755291
[2020-04-05 11:23:20] Start of iteration 1
Error in priorSum_m[, s] : incorrect number of dimensions
Calls: STITCH -> completeSampleIteration -> calculate_updates
In addition: Warning message:
In mclapply(sampleRanges, mc.cores = nCores, FUN = subset_of_complete_iteration,  :
  scheduled cores 3, 4, 5, 8, 9, 11, 13, 16, 17, 19, 20 did not deliver results, all values of the jobs will be affected
Execution halted
```

Do you know if stitch works just with a specific number of cores?

Kind regards,
Felix

**Comment by rwdavies** [comment]
Can you check and confirm it didn't run out of RAM while running? Out of RAM in R parallel computing often crashes in inelegant ways

**Comment by fbartusch** [comment]
Indeed, the job used more than the requested 90gb memory. We will try to reduce the memory footprint using suggestions in the README and other issues.
