### ISSUE TITLE
1.6.3 vs 1.6.5 output differences?

### ISSUE THREAD

**Issue by jelber2** [rwdavies/STITCH#40]
Hi,

I ran STITCH 1.6.3 as it was on bioconda and not yet 1.6.5. Do you except there to be any differences in output between the two versions if not using the bx tag?

Best,
Jean Elbers

**Comment by rwdavies** [comment]
Thanks, I don't know why 1.6.5 hasn't appeared yet, I've asked bioconda core for some help to see if I forgot something. There should not be any differences unless your BAMs have entries in the BX tags, which you would have if you were using 10X or some unique molecular identifier method in your library prep

**Comment by jelber2** [comment]
Ok thanks!! No BX in my BAM files.
