### ISSUE TITLE
sh: /tmp/Rtmp62FCsV/MUYOXGCEGC/files_to_transfer.txt: No such file or directory

### ISSUE THREAD

**Issue by linlin-pp** [rwdavies/STITCH#44]
please help me
Following error

[2021-01-28 20:47:12] Done generating inputs
[2021-01-28 20:47:12] Copying files onto tempdir
sh: /tmp/RtmpFggRHj/ALQXNMCYLW/files_to_transfer.txt: No such file or directory
rsync: failed to open files-from file /tmp/RtmpFggRHj/ALQXNMCYLW/files_to_transfer.txt: No such file or directory
rsync error: syntax or usage error (code 1) at main.c(1578) [client=3.1.3]
[2021-01-28 20:47:13] Done copying files onto tempdir
[2021-01-28 20:47:13] Generate allele count
[2021-01-28 20:47:13] Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection

Error in check_mclapply_OK(out2) : 
  An error occured during STITCH. The first such error is above
Calls: STITCH -> buildAlleleCount -> check_mclapply_OK
In addition: Warning messages:
1: In mclapply(1:length(sampleRanges), mc.cores = nCores, FUN = loadBamAndConvert_across_a_range,  :
  scheduled core 5 did not deliver a result, all values of the job will be affected
2: In mclapply(sampleRanges, mc.cores = nCores, FUN = buildAlleleCount_subfunction,  :
  all scheduled cores encountered errors in user code
Execution halted
srun: error: srv3: task 0: Exited with exit code 1
[xiekr@srv1 chulihou]$ srun -N 1 -w srv3 /nfs2/xiekr/software/STITCH/STITCH.R  --chr=NC_013686.1 --bamlist=629bam.list --posfile=Chr18.txt --outputdir=chr18 --method="diploid" --K=10 --nGen=100 --nCores=55

**Comment by linlin-pp** [comment]
/nfs2/xiekr/software/STITCH/STITCH.R  --chr=NC_013669.1 --bamlist=629bam.list --posfile=Chr1.txt --outputdir=chr1 --method="diploid" --K=10 --nGen=100 --nCores=50

**Comment by rwdavies** [comment]
Did you run out of space in the temporary directory? What does `df -h /tmp/` show?

**Comment by linlin-pp** [comment]
> Did you run out of space in the temporary directory? What does `df -h /tmp/` show?

Hello, can the following storage path be specified by yourself
sh: /tmp/RtmpGHSSBS/YBDJQRBQIN/files_to_transfer.txt: No such file or directory

**Comment by linlin-pp** [comment]
Hello!
Can this path be set by myself
/tmp/RtmpGHSSBS/YBDJQRBQIN/files_to_transfer.txt



At 2021-01-28 21:31:46, "rwdavies" <notifications@github.com> wrote:

Did you run out of space in the temporary directory? What does df -h /tmp/ show?

**Comment by linlin-pp** [comment]
![Uploading image.png…]()

**Comment by rwdavies** [comment]
See option `tempdir` to set an alternate location for a temporary directory. Though if your tempdir is full, that is probably something you want to take a look at

**Comment by linlin-pp** [comment]
> 请参阅`tempdir`为临时目录设置备用位置的选项。尽管如果您的临时目录已满，那可能就是您想要看的东西


The problem has been solved, thank you!
