### ISSUE TITLE
Create plots from output

### ISSUE THREAD

**Issue by nbedelman** [rwdavies/STITCH#57]
Hi! 

I am running STITCH on a compute cluster that does not support X11 and therefore does not generate plots. The runs complete successfully, and I was wondering if there was a way to just load the results locally and generate the plots in RStudio on my desktop. I am able to transfer the results to my computer and re-run the program locally with `regenerateInput = FALSE`, which works, but it would be more convenient and faster to run STITCH on the cluster and just plot the results on my computer. Any advice is greatly appreciated!

Best
Nate

**Comment by alexpiper** [comment]
For anyone who also encounters this issue: Ive had success getting STICH to output plots on our compute cluster which does not support X11, but does have the cairo graphics library. Just run `options(bitmapType='cairo')` before running the `STITCH` command.
