### ISSUE TITLE
Clarification in the usage of the parameter S

### ISSUE THREAD

**Issue by saulpierotti** [rwdavies/STITCH#71]
Hi, I am trying to use STITCH in my work and it is not entirely clear to me in which use-case one may want to use the S parameter,and how does it affect the imputation. The documentation just says "How many sets of founders to use".

Thanks in advance!

**Comment by rwdavies** [comment]
Hi,

In simplest terms, setting S > 1 averages results over multiple rounds of imputation. So for example, setting S = 2 is the same thing as running STITCH twice, and averaging the genotype posteriors and dosages for the two runs. Computational complexity is proportional to S. In my experience testing it out back in the day, it provided a marginal benefit.

Hope that helps,
Robbie
