### ISSUE TITLE
Running from command line 'Execution halted'

### ISSUE THREAD

**Issue by mnbrien** [rwdavies/STITCH#80]
Hi, I am having some trouble running the STITCH script from the command line.

For the test data if I run this command within R, it works fine: 
`STITCH(chr="chr19", bamlist="bamlist.txt", posfile="pos.txt", genfile="gen.txt", K=4, nGen=100, nCores=1, outputdir=".")`

But if I run the same thing on the command line outside of R:
`./STITCH.R --chr=chr19 --bamlist=bamlist.txt --posfile=pos.txt --genfile=gen.txt --outputdir=./ --K=4 --nGen=100 --nCores=1`

I get this error
`Error in STITCH(chr = opt$chr, posfile = opt$posfile, K = opt$K, S = opt$S,  :
  unused arguments (S = opt$S, genetic_map_file = opt$genetic_map_file, reference_shuffleHaplotypeIterations = eval(parse(text = opt$reference_shuffleHaplotypeIterations)), useTempdirWhileWriting = opt$useTempdirWhileWriting, output_haplotype_dosages = opt$output_haplotype_dosages, use_bx_tag = opt$use_bx_tag, bxTagUpperLimit = opt$bxTagUpperLimit, do_phasing = opt$do_phasing, phasing_method = opt$phasing_method, phasing_n_votes = opt$phasing_n_votes)
Execution halted`

Do you have any suggestions? Hope I am not missing something obvious, thanks!

**Comment by rwdavies** [comment]
Apologies I pushed something to master I should have pushed to a branch
Can you `git pull` and try again?

**Comment by mnbrien** [comment]
It's working now, thanks!
