### ISSUE TITLE
It seems a bug in the function "findRecombinedReadsPerSample" at file "heuristics.R"

### ISSUE THREAD

**Issue by wykkyle** [rwdavies/STITCH#85]
![t1](https://github.com/rwdavies/STITCH/assets/20754685/ae8c4fcd-66b9-4be7-9ff4-d2be5b894951)
In the function "findRecombinedReadsPerSample", there's a loop on a selective subset of SampleReads.
The body of the loop is mainly constructed of the function "split_a_read", goes into the function "split_a_read".

![t2](https://github.com/rwdavies/STITCH/assets/20754685/31228e02-6b5a-49fd-8c57-84b7153c8d8f)
In the function "split_a_read", the value of the expression "length(sampleReads)" takes part in the programming.

**Comment by rwdavies** [comment]
Hi,

Sorry for my slow reply, I was on vacation. 

Thanks for the message and finding the specific bug! I've seen errors before around this section of the code but never tracked them down. This was a stupid mistake on my part. I'll go about fixing it now.

Thanks
Robbie
